M48
; DRILL file {KiCad (6.0.10)} date Fri Mar  3 00:14:20 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-03T00:14:20-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.4Y-3.2
X5.5Y-3.4
X5.5Y-3.5
X5.6Y-3.2
X5.7Y-3.1
X5.7Y-3.2035
X5.8Y-3.5
X5.9Y-3.8
X6.0Y-3.0
X6.0Y-3.3
X6.0Y-3.4
X6.075Y-3.225
X6.1Y-3.1
X6.2Y-2.9
T2
X5.3Y-3.1
X5.3Y-3.3
T0
M30
